# Generated by Django 4.2 on 2023-07-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=200, verbose_name="Familiya"),
                ),
                ("last_name", models.CharField(max_length=200, verbose_name="Ism")),
                (
                    "middle_name",
                    models.CharField(max_length=200, verbose_name="Otasining Ismi"),
                ),
                ("passport_number", models.CharField(max_length=150)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("otm", models.CharField(max_length=200)),
                ("speciality", models.CharField(max_length=200)),
                (
                    "study_type",
                    models.CharField(max_length=100, verbose_name="Ta'lim turi"),
                ),
                (
                    "edu_type",
                    models.CharField(max_length=100, verbose_name="Ta'lim shakli"),
                ),
                (
                    "document_number",
                    models.CharField(max_length=100, verbose_name="Diplom raqami"),
                ),
                ("registered_date", models.DateField()),
            ],
        ),
    ]
