# Generated by Django 4.2 on 2023-07-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="birth_date",
            field=models.CharField(
                max_length=50, null=True, verbose_name="Tug'ulgan sanasi"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="otm",
            field=models.CharField(max_length=200, verbose_name="OTM"),
        ),
        migrations.AlterField(
            model_name="student",
            name="passport_number",
            field=models.CharField(max_length=150, verbose_name="Passport raqami"),
        ),
        migrations.AlterField(
            model_name="student",
            name="registered_date",
            field=models.CharField(default="05/07/2023", max_length=50),
        ),
        migrations.AlterField(
            model_name="student",
            name="speciality",
            field=models.CharField(max_length=200, verbose_name="Mutaxasisligi"),
        ),
    ]
