# Generated by Django 4.2 on 2023-07-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0002_alter_student_birth_date_alter_student_otm_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="passport_number",
            field=models.CharField(
                max_length=150, null=True, verbose_name="Passport raqami"
            ),
        ),
    ]
