# Generated by Django 4.2 on 2023-07-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0003_alter_student_passport_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="document_number",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Diplom raqami"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="edu_type",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Ta'lim shakli"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="first_name",
            field=models.CharField(max_length=200, null=True, verbose_name="Familiya"),
        ),
        migrations.AlterField(
            model_name="student",
            name="last_name",
            field=models.CharField(max_length=200, null=True, verbose_name="Ism"),
        ),
        migrations.AlterField(
            model_name="student",
            name="middle_name",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Otasining Ismi"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="otm",
            field=models.CharField(max_length=200, null=True, verbose_name="OTM"),
        ),
        migrations.AlterField(
            model_name="student",
            name="registered_date",
            field=models.CharField(default="05/07/2023", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="speciality",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Mutaxasisligi"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="study_type",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Ta'lim turi"
            ),
        ),
    ]
