# Generated by Django 4.2 on 2023-07-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0005_alter_student_birth_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="birth_date",
            field=models.CharField(
                default="-", max_length=50, null=True, verbose_name="Tug'ulgan sanasi"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="document_number",
            field=models.CharField(
                default="-", max_length=100, null=True, verbose_name="Diplom raqami"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="edu_type",
            field=models.CharField(
                default="-", max_length=100, null=True, verbose_name="Ta'lim shakli"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="first_name",
            field=models.CharField(
                default="-", max_length=200, null=True, verbose_name="Familiya"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="last_name",
            field=models.CharField(
                default="-", max_length=200, null=True, verbose_name="Ism"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="middle_name",
            field=models.CharField(
                default="-", max_length=200, null=True, verbose_name="Otasining Ismi"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="otm",
            field=models.CharField(
                default="-", max_length=200, null=True, verbose_name="OTM"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="passport_number",
            field=models.CharField(
                default="-", max_length=150, null=True, verbose_name="Passport raqami"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="registered_date",
            field=models.CharField(default="-", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="speciality",
            field=models.CharField(
                default="-", max_length=200, null=True, verbose_name="Mutaxasisligi"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="study_type",
            field=models.CharField(
                default="-", max_length=100, null=True, verbose_name="Ta'lim turi"
            ),
        ),
    ]
