# Generated by Django 4.2 on 2023-07-06 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0006_alter_student_birth_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="birth_date",
            field=models.CharField(
                default=datetime.datetime(
                    2023, 7, 6, 10, 8, 6, 957424, tzinfo=datetime.timezone.utc
                ),
                max_length=50,
                verbose_name="Tug'ulgan sanasi",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="student",
            name="document_number",
            field=models.CharField(
                default="", max_length=100, verbose_name="Diplom raqami"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="student",
            name="edu_type",
            field=models.CharField(
                default="", max_length=100, verbose_name="Ta'lim shakli"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="student",
            name="first_name",
            field=models.CharField(default="", max_length=200, verbose_name="Familiya"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="student",
            name="last_name",
            field=models.CharField(default="", max_length=200, verbose_name="Ism"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="student",
            name="middle_name",
            field=models.CharField(
                default="", max_length=200, verbose_name="Otasining Ismi"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="student",
            name="otm",
            field=models.CharField(default="", max_length=200, verbose_name="OTM"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="student",
            name="passport_number",
            field=models.CharField(
                default="", max_length=150, verbose_name="Passport raqami"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="student",
            name="registered_date",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="student",
            name="speciality",
            field=models.CharField(
                default="", max_length=200, verbose_name="Mutaxasisligi"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="student",
            name="study_type",
            field=models.CharField(
                default="", max_length=100, verbose_name="Ta'lim turi"
            ),
            preserve_default=False,
        ),
    ]
