version: "3.3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./static:/home/app/web/static
      - ./media:/home/app/web/media
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
    logging:
      options:
        max-size: 10m

  db:
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${SQL_DB}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
    logging:
      options:
        max-size: 10m

volumes:
  postgres_data:
  static_volume:
  media_volume:
