version: "3.3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8705
    volumes:
      - ./static:/home/app/web/static
      - ./media:/home/app/web/media
    ports:
      - 8705:8705
    env_file:
      - ./.env
    depends_on:
      - db
    logging:
      options:
        max-size: 10m

  db:
    image: postgres:14.0-alpine
    volumes:
      - diplom_postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_TITLE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    logging:
      options:
        max-size: 10m

volumes:
  diplom_postgres_data:
  static_volume:
  media_volume:
