version: "3.9"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8705
    volumes:
      - .:/code
    ports:
      - 8705:8705
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    env_file:
      - ./.env
    environment:
      - PGDATA=/var/lib/postgresql/data/dev/
      - POSTGRES_DB=${DB_TITLE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}